### ISSUE TITLE
Contribuições externas

### ISSUE THREAD

**Issue by karliwson** [fluxoti/3cplusv2-sdk-js#10]
Olá, Mauri.

Sou desenvolvedor em uma empresa cliente da 3C+ (PJA Soluções) e gostaria de saber se você aceita contribuições externas / PRs neste repositório.

Estou desenvolvendo uma integração do seu discador com o nosso CRM, e encontrei este SDK no GitHub por acaso. Senti falta de alguns métodos, por exemplo, na classe `AgentEndpoints`, que fornece apenas alguns wrappers para a API HTTP de vocês. Acredito que seria interessante implementar todos os endpoints, não só do agente, mas também do gestor. Falo isto porque na nossa implementação, utilizamos tanto os endpoints do agente no frontend, quanto os do gestor no backend (utilizamos Node.JS).

Outro ponto é que na página "Integrações" do painel da 3C+, vocês informam que a integração Realtime Socket.IO está descontinuada, porém ela é a única implementada na SDK. Eu poderia contribuir com a implementação WebSocket nativa.

Caso possível, será um prazer ajudar. Obrigado.

**Comment by mauri870** [comment]
Olá @karliwson, no momento a integração Socket.io ainda é a que utilizamos no nosso frontend, mas assim que trocarmos para o Websocket iremos atualizar o sdk. Fique a vontade para contribuir com a integração websocket se asssim desejar.
